import { TaskModel } from '../models/task.model';
import { Category } from '../enums/category.enum';

export const PROJECTS: string[] = [
  'BairesDev - Absence',
  'Pinterest - Pinterest - Infrastructure',
];

export const FOCAL_POINTS: { project: string, focals: string[] }[] = [
  { project: 'BairesDev - Absence', focals: [] },
  {
    project: 'Pinterest - Pinterest - Infrastructure', focals: [
      'Adam Berry',
      'Adam McKenna',
      'June Liu',
      'Paul Bindels',
      'rodrigo.deurtiaga',
      'Scott Beardsley',
      'Tim Moore',
      'Trish Gray',
      'Zhaobang Liu',
    ],
  },
];

export const TASKS: TaskModel[] = [
  { category: Category.ABSENCE, name: 'Personal Reasons' },
  { category: Category.ABSENCE, name: 'National Holiday' },
  { category: Category.ABSENCE, name: 'Compensation day' },
  { category: Category.ABSENCE, name: 'Vacations' },
  { category: Category.ABSENCE, name: 'Sick leave' },
  { category: Category.ABSENCE, name: 'Paid Time Off' },
  { category: Category.ABSENCE, name: 'Unpaid Time Off' },
  { category: Category.ABSENCE, name: 'Other - Absence' },
  { category: Category.ADMINISTRATIVE, name: 'Email revision/answering' },
  { category: Category.ADMINISTRATIVE, name: 'Daily Progress Report' },
  { category: Category.ADMINISTRATIVE, name: 'Weekly Progress Report' },
  { category: Category.ADMINISTRATIVE, name: 'Other - Administrative' },
  { category: Category.DEVELOPMENT, name: 'Architecture definition' },
  { category: Category.DEVELOPMENT, name: 'Code review' },
  { category: Category.DEVELOPMENT, name: 'Demo preparation' },
  { category: Category.DEVELOPMENT, name: 'Deployment' },
  { category: Category.DEVELOPMENT, name: 'Environment setup' },
  { category: Category.DEVELOPMENT, name: 'Features development' },
  { category: Category.DEVELOPMENT, name: 'Test cases development' },
  { category: Category.DEVELOPMENT, name: 'Research / Analysis' },
  { category: Category.DEVELOPMENT, name: 'Spike' },
  { category: Category.DEVELOPMENT, name: 'Bug Fixing' },
  { category: Category.DEVELOPMENT, name: 'Design' },
  { category: Category.DEVELOPMENT, name: 'Writing User Stories' },
  { category: Category.DEVELOPMENT, name: 'Requirements analysis' },
  { category: Category.DEVELOPMENT, name: 'Peer review' },
  { category: Category.DEVELOPMENT, name: 'DB Automation' },
  { category: Category.DEVELOPMENT, name: 'DB Maintenance' },
  { category: Category.DEVELOPMENT, name: 'Research and Learning' },
  { category: Category.DEVELOPMENT, name: 'Configuration' },
  { category: Category.DEVELOPMENT, name: 'Library Upgrade' },
  { category: Category.DEVELOPMENT, name: 'Refactor' },
  { category: Category.DEVELOPMENT, name: 'Support' },
  { category: Category.DEVELOPMENT, name: 'Integration' },
  { category: Category.DEVELOPMENT, name: 'Debug' },
  { category: Category.DEVELOPMENT, name: 'On call' },
  { category: Category.DEVELOPMENT, name: 'Mockups Design' },
  { category: Category.DEVELOPMENT, name: 'Graphic Design' },
  { category: Category.DEVELOPMENT, name: 'Wireframes Design' },
  { category: Category.DEVELOPMENT, name: 'UI definition' },
  { category: Category.DEVELOPMENT, name: 'Other - Development' },
  { category: Category.DOCUMENTATION, name: 'Technical Writing' },
  { category: Category.DOCUMENTATION, name: 'Diagrams drawing' },
  { category: Category.DOCUMENTATION, name: 'Documentation reading' },
  { category: Category.DOCUMENTATION, name: 'Documentation writing' },
  { category: Category.DOCUMENTATION, name: 'Research' },
  { category: Category.DOCUMENTATION, name: 'Other - Documentation' },
  { category: Category.IDLE_TIME, name: 'Travel' },
  { category: Category.IDLE_TIME, name: 'Partial Assigment' },
  { category: Category.IDLE_TIME, name: 'Internet issues' },
  { category: Category.IDLE_TIME, name: 'No assigned tasks' },
  { category: Category.IDLE_TIME, name: 'Other - Idle time' },
  { category: Category.INTERNAL_PROCESS, name: 'Technical Screenings' },
  { category: Category.INTERNAL_PROCESS, name: 'Staffing Technical Interview' },
  { category: Category.INTERNAL_PROCESS, name: 'Coding challenges review' },
  { category: Category.INTERNAL_PROCESS, name: 'Reviewing exams' },
  { category: Category.INTERNAL_PROCESS, name: 'Other - Internal Process' },
  { category: Category.MEETINGS_CLIENT, name: '1-1 with client focal point' },
  { category: Category.MEETINGS_CLIENT, name: 'Backlog refinement meeting' },
  { category: Category.MEETINGS_CLIENT, name: 'Blocker removal meeting' },
  { category: Category.MEETINGS_CLIENT, name: 'Client side training' },
  { category: Category.MEETINGS_CLIENT, name: 'Sprint Planning' },
  { category: Category.MEETINGS_CLIENT, name: 'Sprint Retrospective' },
  { category: Category.MEETINGS_CLIENT, name: 'Sprint Review / Demo' },
  { category: Category.MEETINGS_CLIENT, name: 'Client Meeting' },
  { category: Category.MEETINGS_CLIENT, name: 'Daily Meeting' },
  { category: Category.MEETINGS_CLIENT, name: 'KickOff Meeting' },
  { category: Category.MEETINGS_CLIENT, name: 'Other - Meetings (Client)' },
  { category: Category.MEETINGS_INTERNAL, name: '1:1 meeting with HRBP' },
  { category: Category.MEETINGS_INTERNAL, name: '1:1 meeting with Manager' },
  { category: Category.MEETINGS_INTERNAL, name: 'Team building meeting' },
  {
    category: Category.MEETINGS_INTERNAL,
    name: 'Other - Meetings (Internal)',
  },
  { category: Category.OTHER, name: 'Other' },
  { category: Category.TESTING, name: 'Exploratory' },
  { category: Category.TESTING, name: 'Production Verification' },
  { category: Category.TESTING, name: 'Test Creation/design' },
  { category: Category.TESTING, name: 'Smoke testing' },
  { category: Category.TESTING, name: 'Environment configuration' },
  { category: Category.TESTING, name: 'Functional Testing' },
  { category: Category.TESTING, name: 'Regression testing' },
  { category: Category.TESTING, name: 'Testathon / UAT' },
  { category: Category.TESTING, name: 'Coding' },
  { category: Category.TESTING, name: 'Manual testing' },
  { category: Category.TESTING, name: 'Test case execution' },
  { category: Category.TRAINING_TRAINEE, name: 'Receiving mentoring support' },
  { category: Category.TRAINING_TRAINEE, name: 'Online course' },
  {
    category: Category.TRAINING_TRAINEE,
    name: 'Project Onboarding (Trainee)',
  },
  { category: Category.TRAINING_TRAINEE, name: 'Reading Documentation' },
  { category: Category.TRAINING_TRAINEE, name: 'Internal course' },
  { category: Category.TRAINING_TRAINEE, name: 'Self training' },
  { category: Category.TRAINING_TRAINEE, name: 'Other - Training (Trainee)' },
  { category: Category.TRAINING_TRAINER, name: 'Providing mentoring support' },
  {
    category: Category.TRAINING_TRAINER,
    name: 'Project Onboarding (Trainer)',
  },
];
